use crate::emux8086::{IO, Memory};
use crate::emux8086::alu::add;
use crate::emux8086::instruction_implementations::{add_based_on_modrm_byte, jmp, mov};
use crate::emux8086::mod_byte::DataDirection::{MemToReg, RegToMem};
use crate::emux8086::mod_byte::InstructionWidth::{EightBits, SixteenBits};
use crate::emux8086::registers::Registers;

///
/// # Argument Addressing Codes
///
/// | ARG | Info  |
/// |:---:|:------|
/// | A | Direct address. The instruction has no ModR/M byte; the address of the operand is encoded in the instruction. Applicable, e.g., to far JMP (opcode EA). |
/// | E | A ModR/M byte follows the opcode and specifies the operand. The operand is either a general-purpose register or a memory address. If it is a memory address, the address is computed from a segment register and any of the following values: a base register, an index register, a displacement. |
/// | G | The reg field of the ModR/M byte selects a general register. |
/// | I | Immediate data. The operand value is encoded in subsequent bytes of the instruction. |
/// | J | The instruction contains a relative offset to be added to the address of the subsequent instruction. Applicable, e.g., to short JMP (opcode EB), or LOOP. |
/// | M | The ModR/M byte may refer only to memory. Applicable, e.g., to LES and LDS. |
/// | O | The instruction has no ModR/M byte; the offset of the operand is encoded as a WORD in the instruction. Applicable, e.g., to certain MOVs (opcodes A0 through A3). |
/// | S | The reg field of the ModR/M byte selects a segment register. |
///
/// # Argument Operand Codes
///
/// | ARG | Info  |
/// |:---:|:------|
/// | 0 | Byte argument. Unusual in that arguments of this type are suppressed in ASM output when they have the default value of 10 (0xA). Applicable, e.g., to AAM and AAD. |
/// | b | Byte argument. |
/// | p | 32-bit segment:offset pointer. |
/// | w | Word argument. |
///
/// # Special Argument Codes
///
/// | ARG | Info  |
/// |:---:|:------|
/// | AL | 8-bit register: The low byte of AX |
/// | CL | 8-bit register: The low byte of CX |
/// | DL | 8-bit register: The low byte of DX |
/// | BL | 8-bit register: The low byte of BX |
/// | AH | 8-bit register: The high byte of AX |
/// | CH | 8-bit register: The high byte of CX |
/// | DH | 8-bit register: The high byte of DX |
/// | BH | 8-bit register: The high byte of BX |
/// | AX | 16-bit register: The 'accumulator' register |
/// | CX | 16-bit register: The 'counter' register |
/// | DX | 16-bit register: The 'data' register |
/// | BX | 16-bit register: The 'base' register |
/// | SP | 16-bit register: The 'stack pointer' register |
/// | BP | 16-bit register: The 'base pointer' register |
/// | SI | 16-bit register: The 'source index' register |
/// | DI | 16-bit register: The 'destination index' register |
/// | ES | 16-bit register: The 'extra' segment register |
/// | CS | 16-bit register: The 'code' segment register |
/// | SS | 16-bit register: The 'stack' segment register |
/// | DS | 16-bit register: The 'data' segment register |
/// | 1 | A constant argument of 1, implicit in the opcode, and not represented elsewhere in the instruction. This argument *is* displayed in assembly code. |
/// | 3 | A constant argument of 3, implicit in the opcode, and not represented elsewhere in the instruction. This argument *is* displayed in assembly code. |
/// | M | The ModR/M byte refers to a memory location, however the contents of that memory location are irrelevant; the address itself is the operand of the instruction. Applicable, e.g., to LEA. |
///
pub struct Instruction {
    pub code: u8,
    pub name: &'static str,
    pub args: [&'static str; 2],
    pub ip_change: u8,
    pub execute: fn(io: &mut IO, memory: &mut Memory, registers: &mut Registers),
}

pub static INSTRUCTIONS: &'static [Instruction] = &[
    Instruction { code: 0x00, name: "ADD", args: ["Eb", "Gb"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add_based_on_modrm_byte(memory, registers, EightBits, MemToReg); } },
    Instruction { code: 0x01, name: "ADD", args: ["Ew", "Gw"], ip_change: 0, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add_based_on_modrm_byte(memory, registers, SixteenBits, MemToReg); } },
    Instruction { code: 0x02, name: "ADD", args: ["Gb", "Eb"], ip_change: 0, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add_based_on_modrm_byte(memory, registers, EightBits, RegToMem); } },
    Instruction { code: 0x03, name: "ADD", args: ["Gw", "Ew"], ip_change: 0, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add_based_on_modrm_byte(memory, registers, SixteenBits, RegToMem); } },
    Instruction { code: 0x04, name: "ADD", args: ["AL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add(&memory[registers.read_u16(registers.ip) as usize + 1..], registers.mut_point_to_byte(registers.al)); } },
    Instruction { code: 0x05, name: "ADD", args: ["AX", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { add(&memory[registers.read_u16(registers.ip) as usize + 1..], registers.mut_point_to_word(registers.ax)); } },
    Instruction { code: 0x06, name: "PUSH", args: ["ES", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x07, name: "POP", args: ["ES", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x08, name: "OR", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x09, name: "OR", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0A, name: "OR", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0B, name: "OR", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0C, name: "OR", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0D, name: "OR", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0E, name: "PUSH", args: ["CS", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x0F, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x10, name: "ADC", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x11, name: "ADC", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x12, name: "ADC", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x13, name: "ADC", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x14, name: "ADC", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x15, name: "ADC", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x16, name: "PUSH", args: ["SS", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x17, name: "POP", args: ["SS", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x18, name: "SBB", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x19, name: "SBB", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1A, name: "SBB", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1B, name: "SBB", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1C, name: "SBB", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1D, name: "SBB", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1E, name: "PUSH", args: ["DS", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x1F, name: "POP", args: ["DS", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x20, name: "AND", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x21, name: "AND", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x22, name: "AND", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x23, name: "AND", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x24, name: "AND", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x25, name: "AND", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x26, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x27, name: "DAA", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x28, name: "SUB", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x29, name: "SUB", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2A, name: "SUB", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2B, name: "SUB", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2C, name: "SUB", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2D, name: "SUB", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2E, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x2F, name: "DAS", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x30, name: "XOR", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x31, name: "XOR", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x32, name: "XOR", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x33, name: "XOR", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x34, name: "XOR", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x35, name: "XOR", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x36, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x37, name: "AAA", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x38, name: "CMP", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x39, name: "CMP", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3A, name: "CMP", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3B, name: "CMP", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3C, name: "CMP", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3D, name: "CMP", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3E, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x3F, name: "AAS", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x40, name: "INC", args: ["AX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x41, name: "INC", args: ["CX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x42, name: "INC", args: ["DX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x43, name: "INC", args: ["BX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x44, name: "INC", args: ["SP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x45, name: "INC", args: ["BP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x46, name: "INC", args: ["SI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x47, name: "INC", args: ["DI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x48, name: "DEC", args: ["AX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x49, name: "DEC", args: ["CX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4A, name: "DEC", args: ["DX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4B, name: "DEC", args: ["BX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4C, name: "DEC", args: ["SP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4D, name: "DEC", args: ["BP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4E, name: "DEC", args: ["SI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x4F, name: "DEC", args: ["DI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x50, name: "PUSH", args: ["AX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x51, name: "PUSH", args: ["CX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x52, name: "PUSH", args: ["DX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x53, name: "PUSH", args: ["BX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x54, name: "PUSH", args: ["SP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x55, name: "PUSH", args: ["BP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x56, name: "PUSH", args: ["SI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x57, name: "PUSH", args: ["DI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x58, name: "POP", args: ["AX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x59, name: "POP", args: ["CX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5A, name: "POP", args: ["DX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5B, name: "POP", args: ["BX", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5C, name: "POP", args: ["SP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5D, name: "POP", args: ["BP", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5E, name: "POP", args: ["SI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x5F, name: "POP", args: ["DI", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x60, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x61, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x62, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x63, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x64, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x65, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x66, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x67, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x68, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x69, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6A, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6B, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6C, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6D, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6E, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x6F, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x70, name: "JO", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x71, name: "JNO", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x72, name: "JB", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x73, name: "JNB", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x74, name: "JZ", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x75, name: "JNZ", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x76, name: "JBE", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x77, name: "JA", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x78, name: "JS", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x79, name: "JNS", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7A, name: "JPE", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7B, name: "JPO", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7C, name: "JL", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7D, name: "JGE", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7E, name: "JLE", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x7F, name: "JG", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x80, name: "GRP1", args: ["Eb", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x81, name: "GRP1", args: ["Ew", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x82, name: "GRP1", args: ["Eb", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x83, name: "GRP1", args: ["Ew", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x84, name: "TEST", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x85, name: "TEST", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x86, name: "XCHG", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x87, name: "XCHG", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x88, name: "MOV", args: ["Eb", "Gb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x89, name: "MOV", args: ["Ew", "Gw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8A, name: "MOV", args: ["Gb", "Eb"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8B, name: "MOV", args: ["Gw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8C, name: "MOV", args: ["Ew", "Sw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8D, name: "LEA", args: ["Gw", "M"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8E, name: "MOV", args: ["Sw", "Ew"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x8F, name: "POP", args: ["Ew", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x90, name: "NOP", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x91, name: "XCHG", args: ["CX", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x92, name: "XCHG", args: ["DX", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x93, name: "XCHG", args: ["BX", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x94, name: "XCHG", args: ["SP", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x95, name: "XCHG", args: ["BP", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x96, name: "XCHG", args: ["SI", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x97, name: "XCHG", args: ["DI", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x98, name: "CBW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x99, name: "CWD", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9A, name: "CALL", args: ["Ap", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9B, name: "WAIT", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9C, name: "PUSHF", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9D, name: "POPF", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9E, name: "SAHF", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0x9F, name: "LAHF", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA0, name: "MOV", args: ["AL", "Ob"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA1, name: "MOV", args: ["AX", "Ow"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA2, name: "MOV", args: ["Ob", "AL"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA3, name: "MOV", args: ["Ow", "AX"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA4, name: "MOVSB", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA5, name: "MOVSW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA6, name: "CMPSB", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA7, name: "CMPSW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA8, name: "TEST", args: ["AL", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xA9, name: "TEST", args: ["AX", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAA, name: "STOSB", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAB, name: "STOSW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAC, name: "LODSB", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAD, name: "LODSW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAE, name: "SCASB", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xAF, name: "SCASW", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xB0, name: "MOV", args: ["AL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.ax), 0, 1); } },
    Instruction { code: 0xB1, name: "MOV", args: ["CL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.cl), 0, 1); } },
    Instruction { code: 0xB2, name: "MOV", args: ["DL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.dl), 0, 1); } },
    Instruction { code: 0xB3, name: "MOV", args: ["BL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.bl), 0, 1); } },
    Instruction { code: 0xB4, name: "MOV", args: ["AH", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.ah), 0, 1); } },
    Instruction { code: 0xB5, name: "MOV", args: ["CH", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.ch), 0, 1); } },
    Instruction { code: 0xB6, name: "MOV", args: ["DH", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.dh), 0, 1); } },
    Instruction { code: 0xB7, name: "MOV", args: ["BH", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.bh), 0, 1); } },
    Instruction { code: 0xB8, name: "MOV", args: ["AX", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.ax), 0, 2); } },
    Instruction { code: 0xB9, name: "MOV", args: ["CX", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.cx), 0, 2); } },
    Instruction { code: 0xBA, name: "MOV", args: ["DX", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.dx), 0, 2); } },
    Instruction { code: 0xBB, name: "MOV", args: ["BX", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.bx), 0, 2); } },
    Instruction { code: 0xBC, name: "MOV", args: ["SP", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.sp), 0, 2); } },
    Instruction { code: 0xBD, name: "MOV", args: ["BP", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.bp), 0, 2); } },
    Instruction { code: 0xBE, name: "MOV", args: ["SI", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.si), 0, 2); } },
    Instruction { code: 0xBF, name: "MOV", args: ["DI", "Iw"], ip_change: 3, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*memory, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.di), 0, 2); } },
    Instruction { code: 0xC0, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC1, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC2, name: "RET", args: ["Iw", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC3, name: "RET", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC4, name: "LES", args: ["Gw", "Mp"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC5, name: "LDS", args: ["Gw", "Mp"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC6, name: "MOV", args: ["Eb", "Ib"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC7, name: "MOV", args: ["Ew", "Iw"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC8, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xC9, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCA, name: "RETF", args: ["Iw", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCB, name: "RETF", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCC, name: "INT", args: ["3", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCD, name: "INT", args: ["Ib", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCE, name: "INTO", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xCF, name: "IRET", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD0, name: "GRP2", args: ["Eb", "1"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD1, name: "GRP2", args: ["Ew", "1"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD2, name: "GRP2", args: ["Eb", "CL"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD3, name: "GRP2", args: ["Ew", "CL"], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD4, name: "AAM", args: ["I0", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD5, name: "AAD", args: ["I0", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD6, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD7, name: "XLAT", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD8, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xD9, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDA, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDB, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDC, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDD, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDE, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xDF, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE0, name: "LOOPNZ", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE1, name: "LOOPZ", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE2, name: "LOOP", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE3, name: "JCXZ", args: ["Jb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE4, name: "IN", args: ["AL", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*io, registers.read_u16(registers.ip) + 1, registers.mut_point_to_byte(registers.ax), 0, 1); } },
    Instruction { code: 0xE5, name: "IN", args: ["AX", "Ib"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*io, registers.read_u16(registers.ip) + 1, registers.mut_point_to_word(registers.ax), 0, 2); } },
    Instruction { code: 0xE6, name: "OUT", args: ["Ib", "AL"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(registers.point_to_byte(registers.ax), 0, io, registers.read_u16(registers.ip) + 1, 1); } },
    Instruction { code: 0xE7, name: "OUT", args: ["Ib", "AX"], ip_change: 2, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(registers.point_to_word(registers.ax), 0, io, registers.read_u16(registers.ip) + 1, 2); } },
    Instruction { code: 0xE8, name: "CALL", args: ["Jw", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xE9, name: "JMP", args: ["Jw", ""], ip_change: 0, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| {jmp(registers, memory[registers.read_u16(registers.ip) as usize] as usize) } },
    Instruction { code: 0xEA, name: "JMP", args: ["Ap", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xEB, name: "JMP", args: ["Jb", ""], ip_change: 1, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { jmp(registers, memory[registers.read_u16(registers.ip) as usize] as usize); } },
    Instruction { code: 0xEC, name: "IN", args: ["AL", "DX"], ip_change: 1, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*io, registers.read_u16(registers.dx), registers.mut_point_to_byte(registers.al), 0, 1); } },
    Instruction { code: 0xED, name: "IN", args: ["AX", "DX"], ip_change: 1, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(&*io, registers.read_u16(registers.dx), registers.mut_point_to_byte(registers.ax), 0, 2); } },
    Instruction { code: 0xEE, name: "OUT", args: ["DX", "AL"], ip_change: 1, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(registers.point_to_byte(registers.al), 0, io, registers.read_u16(registers.dx), 1); } },
    Instruction { code: 0xEF, name: "OUT", args: ["DX", "AX"], ip_change: 1, execute: |io: &mut IO, memory: &mut Memory, registers: &mut Registers| { mov(registers.point_to_word(registers.ax), 0, io, registers.read_u16(registers.dx), 2); } },
    Instruction { code: 0xF0, name: "LOCK", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF1, name: "--", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF2, name: "REPNZ", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF3, name: "REPZ", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF4, name: "HLT", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF5, name: "CMC", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF6, name: "GRP3a", args: ["Eb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF7, name: "GRP3b", args: ["Ew", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF8, name: "CLC", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xF9, name: "STC", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFA, name: "CLI", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFB, name: "STI", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFC, name: "CLD", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFD, name: "STD", args: ["", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFE, name: "GRP4", args: ["Eb", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
    Instruction { code: 0xFF, name: "GRP5", args: ["Ew", ""], ip_change: 0, execute: |_io: &mut IO, memory: &mut Memory, registers: &mut Registers| {} },
];
